/**
 * Layer 6 — Asset Generation & Optimization Pipeline
 * FFmpeg + Sharp for frame extraction, compression, spritesheet generation
 */

export interface FFmpegConfig {
  inputPath: string;
  outputDir: string;
  format: 'webp' | 'avif' | 'png' | 'jpg';
  quality: number; // 1-100
  fps?: number;
  width?: number;
  height?: number;
  startTime?: string;
  duration?: string;
}

/**
 * Generate FFmpeg commands for frame extraction
 */
export function generateFFmpegCommands(config: FFmpegConfig): {
  extractFrames: string;
  createSpritesheet: string;
  createScrollVideo: string;
  createThumbnail: string;
} {
  const { inputPath, outputDir, format, quality, fps = 24, width = 1440, height } = config;
  const size = height ? `${width}x${height}` : `${width}:-1`;
  const qualityFlag = format === 'webp' ? `-q:v ${quality}` : `-q:v ${Math.round((100 - quality) * 0.3)}`;

  return {
    // Extract individual frames
    extractFrames: `ffmpeg -i "${inputPath}" -vf "fps=${fps},scale=${size}" -c:v libwebp ${qualityFlag} "${outputDir}/frame_%04d.${format}"`,

    // Create spritesheet (requires ImageMagick or Sharp after frame extraction)
    createSpritesheet: `# First extract frames, then use Sharp to combine:
# npx sharp-cli -i frames/*.webp --tile 10x10 -o spritesheet.webp`,

    // Create scroll-scrubbable video (every frame is keyframe)
    createScrollVideo: `ffmpeg -i "${inputPath}" -c:v libx264 -crf 28 -g 1 -preset veryfast -vf "scale=${size}" -an "${outputDir}/scroll_ready.mp4"`,

    // Create thumbnail/fallback
    createThumbnail: `ffmpeg -i "${inputPath}" -ss 00:00:00.000 -vframes 1 -vf "scale=${size}" -c:v libwebp -q:v 80 "${outputDir}/fallback.${format}"`,
  };
}

export interface SharpConfig {
  inputDir: string;
  outputDir: string;
  format: 'webp' | 'avif' | 'png';
  quality: number;
  width?: number;
  height?: number;
}

/**
 * Generate Sharp batch processing script
 */
export function generateSharpScript(config: SharpConfig): string {
  const { inputDir, outputDir, format, quality, width = 1440, height } = config;

  return `
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const inputDir = '${inputDir}';
const outputDir = '${outputDir}';
const format = '${format}';
const quality = ${quality};
const width = ${width};
const height = ${height || 'null'};

if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

const frames = fs.readdirSync(inputDir)
  .filter(f => /\\.(png|jpg|webp|avif|tiff)$/i.test(f))
  .sort();

console.log(\`Processing \${frames.length} frames...\`);

async function processFrames() {
  for (let i = 0; i < frames.length; i++) {
    const input = path.join(inputDir, frames[i]);
    const output = path.join(outputDir, \`frame_\${String(i+1).padStart(4,'0')}.\${format}\`);
    
    let pipeline = sharp(input).resize(width, height, { fit: 'inside', withoutEnlargement: true });
    
    switch (format) {
      case 'webp': pipeline = pipeline.webp({ quality }); break;
      case 'avif': pipeline = pipeline.avif({ quality: Math.round(quality * 0.8) }); break;
      case 'png': pipeline = pipeline.png({ compressionLevel: 9 }); break;
    }
    
    await pipeline.toFile(output);
    
    if (i % 50 === 0) console.log(\`  \${i+1}/\${frames.length}\`);
  }
  
  console.log('Done! Generating spritesheet...');
  
  // Generate spritesheet
  const cols = Math.ceil(Math.sqrt(frames.length));
  const rows = Math.ceil(frames.length / cols);
  
  const sample = sharp(path.join(outputDir, 'frame_0001.' + format));
  const metadata = await sample.metadata();
  const frameW = metadata.width;
  const frameH = metadata.height;
  
  const composites = [];
  for (let i = 0; i < frames.length; i++) {
    const col = i % cols;
    const row = Math.floor(i / cols);
    composites.push({
      input: path.join(outputDir, \`frame_\${String(i+1).padStart(4,'0')}.\${format}\`),
      left: col * frameW,
      top: row * frameH,
    });
  }
  
  await sharp({
    create: { width: cols * frameW, height: rows * frameH, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
  })
    .composite(composites)
    .webp({ quality })
    .toFile(path.join(outputDir, 'spritesheet.webp'));
  
  console.log(\`Spritesheet: \${cols}x\${rows} = \${frames.length} frames at \${cols*frameW}x\${rows*frameH}\`);
}

processFrames().catch(console.error);
`;
}

/**
 * Generate a complete asset pipeline script
 */
export function generatePipelineScript(config: {
  videoPath: string;
  outputDir: string;
  frameCount: number;
  width: number;
  height?: number;
}): string {
  const { videoPath, outputDir, frameCount, width, height } = config;
  const size = height ? `${width}x${height}` : `${width}:-1`;

  return `#!/bin/bash
# Ideawake Asset Pipeline
# Generated by RIG Design Studio V10

set -e

INPUT="${videoPath}"
OUTPUT="${outputDir}"
FRAMES=${frameCount}
SIZE="${size}"

echo "=== Ideawake Asset Pipeline ==="
echo "Input: $INPUT"
echo "Output: $OUTPUT"
echo "Frames: $FRAMES"
echo "Size: $SIZE"

mkdir -p "$OUTPUT/frames"
mkdir -p "$OUTPUT/optimized"

# Step 1: Extract frames
echo "Step 1: Extracting frames..."
ffmpeg -i "$INPUT" -vf "fps=24,scale=$SIZE" -c:v libwebp -q:v 80 "$OUTPUT/frames/frame_%04d.webp"

# Step 2: Count extracted frames
EXTRACTED=$(ls "$OUTPUT/frames"/*.webp 2>/dev/null | wc -l)
echo "Extracted $EXTRACTED frames"

# Step 3: Generate fallback thumbnail
echo "Step 2: Generating fallback thumbnail..."
ffmpeg -i "$INPUT" -ss 00:00:00.000 -vframes 1 -vf "scale=$SIZE" -c:v libwebp -q:v 80 "$OUTPUT/fallback.webp"

# Step 4: Generate scroll-ready video
echo "Step 3: Generating scroll-ready video..."
ffmpeg -i "$INPUT" -c:v libx264 -crf 28 -g 1 -preset veryfast -vf "scale=$SIZE" -an "$OUTPUT/scroll_ready.mp4"

echo "=== Pipeline complete ==="
echo "Frames: $OUTPUT/frames/"
echo "Fallback: $OUTPUT/fallback.webp"
echo "Video: $OUTPUT/scroll_ready.mp4"

# Step 5: Generate spritesheet (requires Node.js + Sharp)
echo "Step 4: Generating spritesheet..."
node -e "
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

async function buildSpritesheet() {
  const frames = fs.readdirSync('$OUTPUT/frames').filter(f => f.endsWith('.webp')).sort();
  const cols = Math.ceil(Math.sqrt(frames.length));
  const rows = Math.ceil(frames.length / cols);
  
  const meta = await sharp(path.join('$OUTPUT/frames', frames[0])).metadata();
  const composites = frames.map((f, i) => ({
    input: path.join('$OUTPUT/frames', f),
    left: (i % cols) * meta.width,
    top: Math.floor(i / cols) * meta.height,
  }));
  
  await sharp({
    create: { width: cols * meta.width, height: rows * meta.height, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } }
  }).composite(composites).webp({ quality: 80 }).toFile('$OUTPUT/spritesheet.webp');
  
  console.log('Spritesheet: ' + cols + 'x' + rows + ' = ' + frames.length + ' frames');
}
buildSpritesheet().catch(console.error);
"
`;
}
